version: '3.5'

services:
  inmem:
    image: redis
    networks:
      - test-quik-tech

  db:
    container_name: "wallet_db"
    platform: linux/x86_64
    image: mysql:latest
    networks:
      - test-quik-tech
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "walletdb"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  wallet-test-quik-tech:
    image: wallet-test-quik-tech
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    environment:
      ENV: local
      VERSION: 1.0.0
      LOG_LEVEL: debug # panic / fatal / error / warning / info / debug / trace
      
      ENDPOINT_URL: /api/v1/wallets
      API_PORT: 8081

      MYSQL_DATABASE: "walletdb"
      MYSQL_USER: "tester"
      MYSQL_PASSWORD: "secret"
      MYSQL_PORT: 3306
      MYSQL_TIMEOUT_SEC: 30

      REDIS_HOST: inmem
      REDIS_PORT: 6379
      REDIS_EXPIRY_SEC: 300

      SESSION_EXPIRY_SEC: 300

    ports:
      - "9001:8081"
      
    networks:
      - test-quik-tech
      
networks: 
  test-quik-tech: 
    external: true
    name: test-quik-tech 

volumes:
  mysql_data: