version: '3.5'

services:
  inmem:
    image: redis
    networks:
      - test-quik-tech

  wallet-test-quik-tech:
    image: wallet-test-quik-tech
    environment:
      ENV: local
      VERSION: 1.0.0
      
      ENDPOINT_URL: /api/v1/wallets
      API_PORT: 8081

      REDIS_HOST: inmem
      REDIS_PORT: 6379
      REDIS_EXPIRY_SEC: 10

      SESSION_EXPIRY_SEC: 10

    ports:
      - "9001:8081"
      
    networks:
      - test-quik-tech
      
networks: 
  test-quik-tech: 
    external: true
    name: test-quik-tech 